import {
  createDocument,
  createFolder,
  duplicateWorkspaceEntry,
  handleWorkspaceChanged,
  emptyWorkspaceTrash,
  loadDocuments,
  loadWorkspaceImage,
  loadWorkspacePreview,
  loadWorkspaceTrash,
  moveWorkspaceEntry,
  openDocument,
  openWithSystem,
  restoreWorkspaceTrash,
  search,
  trashWorkspaceEntry,
  writeImage,
} from './workspace/documents'
import {
  abortGitOperation,
  checkoutBranch,
  createBranch,
  deleteBranch,
  gitAction,
  resolveConflict,
  resolveConflictContent,
  setPathStaged,
  showDiff,
  showUnsavedDiff,
  showWorktreeDiff,
  sync,
} from './workspace/git'
import {
  chooseExternalVersion,
  closeTab,
  flushAll,
  updateActiveContent,
} from './workspace/persistence'
import {
  activateWorkspace,
  addWorkspace,
  enableWorkspaceGit,
  forgetActiveWorkspace,
  handleWorkspaceForgotten,
  initializeWorkspace,
  previewWorkspaceGitBaseline,
  openSearchResult,
  refreshActive,
  selectWorktree,
} from './workspace/workspaces'
import {
  activeWorkspace,
  activeWorkspaceId,
  activeRoot,
  activeStatus,
  activeTab,
  activeTabKey,
  activeDocumentIsFavorite,
  activeDocumentCharacterLimit,
  activeWorktree,
  branches,
  clearNotice,
  conflicts,
  crossWorktreeMatches,
  diffOpen,
  diffResult,
  documents,
  error,
  externalComparison,
  entries,
  favoriteDocuments,
  filePreview,
  gitBusyAction,
  loading,
  message,
  pendingOperation,
  recentDocuments,
  workspaces,
  searchQuery,
  searchResults,
  searchInProgress,
  syncing,
  tabs,
  trashEntries,
  toggleActiveDocumentFavorite,
  toggleFavoritePath,
} from './workspace/state'
import { shallowReadonly } from 'vue'
import {
  closeDiff,
  closeFilePreview,
  selectTab,
  setError,
  setNotice,
  setSearchQuery,
} from './workspace/state'

export function useWorkspace() {
  return {
    workspaces: shallowReadonly(workspaces),
    activeWorkspaceId: shallowReadonly(activeWorkspaceId),
    activeWorkspace: shallowReadonly(activeWorkspace),
    activeWorktree: shallowReadonly(activeWorktree),
    activeRoot: shallowReadonly(activeRoot),
    activeStatus: shallowReadonly(activeStatus),
    entries: shallowReadonly(entries),
    documents: shallowReadonly(documents),
    branches: shallowReadonly(branches),
    recentDocuments: shallowReadonly(recentDocuments),
    favoriteDocuments: shallowReadonly(favoriteDocuments),
    tabs: shallowReadonly(tabs),
    trashEntries: shallowReadonly(trashEntries),
    activeTab: shallowReadonly(activeTab),
    activeDocumentCharacterLimit: shallowReadonly(activeDocumentCharacterLimit),
    activeTabKey: shallowReadonly(activeTabKey),
    searchQuery: shallowReadonly(searchQuery),
    searchResults: shallowReadonly(searchResults),
    searchInProgress: shallowReadonly(searchInProgress),
    crossWorktreeMatches: shallowReadonly(crossWorktreeMatches),
    loading: shallowReadonly(loading),
    syncing: shallowReadonly(syncing),
    gitBusyAction: shallowReadonly(gitBusyAction),
    message: shallowReadonly(message),
    error: shallowReadonly(error),
    diffResult: shallowReadonly(diffResult),
    diffOpen: shallowReadonly(diffOpen),
    filePreview: shallowReadonly(filePreview),
    conflicts: shallowReadonly(conflicts),
    pendingOperation: shallowReadonly(pendingOperation),
    externalComparison: shallowReadonly(externalComparison),
    initializeWorkspace,
    addWorkspace,
    forgetActiveWorkspace,
    handleWorkspaceForgotten,
    activateWorkspace,
    enableWorkspaceGit,
    previewWorkspaceGitBaseline,
    selectWorktree,
    loadDocuments,
    refreshActive,
    handleWorkspaceChanged,
    loadWorkspaceImage,
    loadWorkspacePreview,
    openDocument,
    createDocument,
    createFolder,
    moveWorkspaceEntry,
    duplicateWorkspaceEntry,
    trashWorkspaceEntry,
    openWithSystem,
    loadWorkspaceTrash,
    restoreWorkspaceTrash,
    emptyWorkspaceTrash,
    updateActiveContent,
    writeImage,
    closeTab,
    search,
    openSearchResult,
    showDiff,
    showWorktreeDiff,
    showUnsavedDiff,
    sync,
    resolveConflict,
    resolveConflictContent,
    abortGitOperation,
    gitAction,
    setPathStaged,
    createBranch,
    checkoutBranch,
    deleteBranch,
    chooseExternalVersion,
    flushAll,
    clearNotice,
    reportError: setError,
    notify: setNotice,
    selectTab,
    setSearchQuery,
    closeDiff,
    closeFilePreview,
    activeDocumentIsFavorite,
    toggleActiveDocumentFavorite,
    toggleFavoritePath,
  }
}

export type WorkspaceApi = ReturnType<typeof useWorkspace>
