import {
  createDocument,
  handleRepositoryChanged,
  loadDocuments,
  loadRepositoryImage,
  openDocument,
  search,
  writeImage,
} from './workspace/documents'
import {
  abortGitOperation,
  checkoutBranch,
  createBranch,
  deleteBranch,
  gitAction,
  resolveConflict,
  resolveConflictContent,
  setPathStaged,
  showDiff,
  showUnsavedDiff,
  showWorktreeDiff,
  sync,
} from './workspace/git'
import {
  chooseExternalVersion,
  closeTab,
  flushAll,
  updateActiveContent,
} from './workspace/persistence'
import {
  activateRepository,
  addRepository,
  forgetActiveRepository,
  handleRepositoryForgotten,
  initializeWorkspace,
  openSearchResult,
  refreshActive,
  selectWorktree,
} from './workspace/repositories'
import {
  activeRepository,
  activeRepositoryId,
  activeRoot,
  activeStatus,
  activeTab,
  activeTabKey,
  activeWorktree,
  branches,
  clearNotice,
  conflicts,
  crossWorktreeMatches,
  diffOpen,
  diffResult,
  documents,
  error,
  externalComparison,
  filteredDocuments,
  imagePreview,
  loading,
  message,
  pendingOperation,
  quickOpenDocuments,
  repositories,
  searchQuery,
  syncing,
  tabs,
} from './workspace/state'

export function useWorkspace() {
  return {
    repositories,
    activeRepositoryId,
    activeRepository,
    activeWorktree,
    activeRoot,
    activeStatus,
    documents,
    branches,
    filteredDocuments,
    quickOpenDocuments,
    tabs,
    activeTab,
    activeTabKey,
    searchQuery,
    crossWorktreeMatches,
    loading,
    syncing,
    message,
    error,
    diffResult,
    diffOpen,
    imagePreview,
    conflicts,
    pendingOperation,
    externalComparison,
    initializeWorkspace,
    addRepository,
    forgetActiveRepository,
    handleRepositoryForgotten,
    activateRepository,
    selectWorktree,
    loadDocuments,
    refreshActive,
    handleRepositoryChanged,
    loadRepositoryImage,
    openDocument,
    createDocument,
    updateActiveContent,
    writeImage,
    closeTab,
    search,
    openSearchResult,
    showDiff,
    showWorktreeDiff,
    showUnsavedDiff,
    sync,
    resolveConflict,
    resolveConflictContent,
    abortGitOperation,
    gitAction,
    setPathStaged,
    createBranch,
    checkoutBranch,
    deleteBranch,
    chooseExternalVersion,
    flushAll,
    clearNotice,
  }
}
